=== Humera-hub/Online-Book-Store/lib.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (bid, title, author*, pub, cover, pages, rating, value, location, comment?)>
<!ELEMENT bid EMPTY>
<!ATTLIST bid bno CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author nickname CDATA #IMPLIED>
<!ELEMENT pub (#PCDATA)>
<!ELEMENT cover EMPTY>
<!ATTLIST cover make (hardbound | paperbound) #REQUIRED>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT rating EMPTY>
<!ATTLIST rating quality (poor | avg | good | excellent) #REQUIRED>
<!ELEMENT value EMPTY>
<!ATTLIST value mkt CDATA #REQUIRED price CDATA #REQUIRED>
<!ELEMENT location EMPTY>
<!ATTLIST location place CDATA #FIXED "CVSR">
<!ELEMENT comment (#PCDATA)>

=== Humera-hub/Online-Book-Store/WT-Lab/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "lib.dtd">
<library>
  <book>
    <bid bno="100"/>
    <title>Java Programming</title>
    <author>abc</author>
    <author nickname="who">xyz</author>
    <pub>BPB pub</pub>
    <cover make="hardbound"/>
    <pages>300</pages>
    <rating quality="good"/>
    <value mkt="whole sale" price="250.00"/>
    <location place="CVSR"/>
    <comment>this is a good book</comment>
  </book>
  <book>
    <bid bno="101"/>
    <title>C Programming</title>
    <author>balaguruswami</author>
    <pub>BPB pub</pub>
    <cover make="hardbound"/>
    <pages>250</pages>
    <rating quality="excellent"/>
    <value mkt="market" price="300.00"/>
    <location place="CVSR"/>
  </book>
</library>
